"""PBI-41: reference lookups for form dropdowns + document type scoping.

Free-text inputs for gender/nationality/marital status let the same concept
in as a dozen spellings. Viewpoint already solved this: LookTables/LookValues
hold the controlled vocabularies. These are lifted from it verbatim (GEND,
MART, CNTR, CURR, COST, OSTS, ADTP, ADRT) and baked in as literals, so a fresh
deployment needs no Viewpoint connection.

Nationality is the exception: Viewpoint has NO lookup for it, only free text.
The 114 demonyms actually present in the data are seeded verbatim so every
existing person still matches an option, plus common ones that were missing.

Also scopes document types to what can own them (a Certificate of Incorporation
is not a person document) and repairs the em-dash mojibake in two labels.

Revision ID: 013
Revises: 012
"""
from alembic import op
import sqlalchemy as sa

revision = "013"
down_revision = "012"
branch_labels = None
depends_on = None

# (category, code, label, sort_order)
LOOKUPS = [
    ('gender', 'F', 'Female', 0),
    ('gender', 'M', 'Male', 10),
    ('gender', 'N', 'Neutral', 20),
    ('gender', 'U', 'Unknown', 30),
    ('marital_status', 'DI', 'Divorced', 0),
    ('marital_status', 'MA', 'Married', 10),
    ('marital_status', 'SE', 'Separated', 20),
    ('marital_status', 'SI', 'Single', 30),
    ('marital_status', 'UN', 'Unknown', 40),
    ('marital_status', 'WI', 'Widowed/Widower', 50),
    ('country', 'AF', 'Afghanistan', 0),
    ('country', 'AX', 'Aland Islands', 10),
    ('country', 'AL', 'Albania', 20),
    ('country', 'GB-ALD', 'Alderney, C.I.', 30),
    ('country', 'DZ', 'Algeria', 40),
    ('country', 'AS', 'American Samoa', 50),
    ('country', 'AD', 'Andorra', 60),
    ('country', 'AO', 'Angola', 70),
    ('country', 'AI', 'Anguilla', 80),
    ('country', 'AQ', 'Antarctica', 90),
    ('country', 'AG', 'Antigua and Barbuda', 100),
    ('country', 'AR', 'Argentina', 110),
    ('country', 'AM', 'Armenia', 120),
    ('country', 'AW', 'Aruba', 130),
    ('country', 'AU', 'Australia', 140),
    ('country', 'AT', 'Austria', 150),
    ('country', 'AZ', 'Azerbaijan', 160),
    ('country', 'BS', 'Bahamas', 170),
    ('country', 'BH', 'Bahrain', 180),
    ('country', 'BD', 'Bangladesh', 190),
    ('country', 'BB', 'Barbados', 200),
    ('country', 'BY', 'Belarus', 210),
    ('country', 'BE', 'Belgium', 220),
    ('country', 'BZ', 'Belize', 230),
    ('country', 'BJ', 'Benin', 240),
    ('country', 'BM', 'Bermuda', 250),
    ('country', 'BQ', 'BES Islands', 260),
    ('country', 'BT', 'Bhutan', 270),
    ('country', 'BO', 'Bolivia', 280),
    ('country', 'BA', 'Bosnia and Herzegovina', 290),
    ('country', 'BW', 'Botswana', 300),
    ('country', 'BV', 'Bouvet Island', 310),
    ('country', 'BR', 'Brazil', 320),
    ('country', 'IO', 'British Indian Ocean Territory', 330),
    ('country', 'VG', 'British Virgin Islands', 340),
    ('country', 'BN', 'Brunei Darussalam', 350),
    ('country', 'BG', 'Bulgaria', 360),
    ('country', 'BF', 'Burkina Faso', 370),
    ('country', 'BI', 'Burundi', 380),
    ('country', 'KH', 'Cambodia', 390),
    ('country', 'CM', 'Cameroon', 400),
    ('country', 'CA', 'Canada', 410),
    ('country', 'CV', 'Cape Verde', 420),
    ('country', 'KY', 'Cayman Islands', 430),
    ('country', 'CF', 'Central African Republic', 440),
    ('country', 'TD', 'Chad', 450),
    ('country', 'CL', 'Chile', 460),
    ('country', 'CN', 'China', 470),
    ('country', 'CX', 'Christmas Island', 480),
    ('country', 'CC', 'Cocos (Keeling) Islands', 490),
    ('country', 'CO', 'Colombia', 500),
    ('country', 'KM', 'Comoros', 510),
    ('country', 'CG', 'Congo', 520),
    ('country', 'CK', 'Cook Islands', 530),
    ('country', 'CR', 'Costa Rica', 540),
    ('country', 'CI', "Cote d'Ivoire", 550),
    ('country', 'HR', 'Croatia', 560),
    ('country', 'CU', 'Cuba', 570),
    ('country', 'CW', 'Curaçao', 580),
    ('country', 'CY', 'Cyprus', 590),
    ('country', 'CZ', 'Czech Republic', 600),
    ('country', 'US-DE', 'Delaware', 610),
    ('country', 'KP', "Democratic People's Republic of Korea", 620),
    ('country', 'DK', 'Denmark', 630),
    ('country', 'DJ', 'Djibouti', 640),
    ('country', 'DM', 'Dominica', 650),
    ('country', 'DO', 'Dominican Republic', 660),
    ('country', 'EC', 'Ecuador', 670),
    ('country', 'EG', 'Egypt', 680),
    ('country', 'SV', 'El Salvador', 690),
    ('country', 'GB-ENG', 'England', 700),
    ('country', 'GB-EAW', 'England & Wales', 710),
    ('country', 'GQ', 'Equatorial Guinea', 720),
    ('country', 'ER', 'Eritrea', 730),
    ('country', 'EE', 'Estonia', 740),
    ('country', 'ET', 'Ethiopia', 750),
    ('country', 'FK', 'Falkland Islands (Malvinas)', 760),
    ('country', 'FO', 'Faroe Islands', 770),
    ('country', 'FM', 'Federated States of Micronesia', 780),
    ('country', 'FJ', 'Fiji', 790),
    ('country', 'FI', 'Finland', 800),
    ('country', 'FR', 'France', 810),
    ('country', 'GF', 'French Guiana', 820),
    ('country', 'PF', 'French Polynesia', 830),
    ('country', 'TF', 'French Southern Territories', 840),
    ('country', 'GA', 'Gabon', 850),
    ('country', 'GM', 'Gambia', 860),
    ('country', 'GE', 'Georgia', 870),
    ('country', 'DE', 'Germany', 880),
    ('country', 'GH', 'Ghana', 890),
    ('country', 'GI', 'Gibraltar', 900),
    ('country', 'GR', 'Greece', 910),
    ('country', 'GL', 'Greenland', 920),
    ('country', 'GD', 'Grenada', 930),
    ('country', 'GP', 'Guadeloupe', 940),
    ('country', 'GU', 'Guam', 950),
    ('country', 'GT', 'Guatemala', 960),
    ('country', 'GG', 'Guernsey', 970),
    ('country', 'GN', 'Guinea', 980),
    ('country', 'GW', 'Guinea-Bissau', 990),
    ('country', 'GY', 'Guyana', 1000),
    ('country', 'HT', 'Haiti', 1010),
    ('country', 'HM', 'Heard Island and McDonald Islands', 1020),
    ('country', 'HN', 'Honduras', 1030),
    ('country', 'HK', 'Hong Kong', 1040),
    ('country', 'HU', 'Hungary', 1050),
    ('country', 'IS', 'Iceland', 1060),
    ('country', 'IN', 'India', 1070),
    ('country', 'ID', 'Indonesia', 1080),
    ('country', 'IQ', 'Iraq', 1090),
    ('country', 'IE', 'Ireland', 1100),
    ('country', 'IR', 'Islamic Republic of Iran', 1110),
    ('country', 'IM', 'Isle of Man', 1120),
    ('country', 'IL', 'Israel', 1130),
    ('country', 'IT', 'Italy', 1140),
    ('country', 'JM', 'Jamaica', 1150),
    ('country', 'JP', 'Japan', 1160),
    ('country', 'JE', 'Jersey', 1170),
    ('country', 'JO', 'Jordan', 1180),
    ('country', 'KZ', 'Kazakhstan', 1190),
    ('country', 'KE', 'Kenya', 1200),
    ('country', 'KI', 'Kiribati', 1210),
    ('country', 'XK', 'Kosovo', 1220),
    ('country', 'KW', 'Kuwait', 1230),
    ('country', 'KG', 'Kyrgyzstan', 1240),
    ('country', 'MY-15', 'Labuan', 1250),
    ('country', 'LA', "Lao Peoples' Democratic Republic", 1260),
    ('country', 'LV', 'Latvia', 1270),
    ('country', 'LB', 'Lebanon', 1280),
    ('country', 'LS', 'Lesotho', 1290),
    ('country', 'LR', 'Liberia', 1300),
    ('country', 'LY', 'Libya', 1310),
    ('country', 'LI', 'Liechtenstein', 1320),
    ('country', 'LT', 'Lithuania', 1330),
    ('country', 'LU', 'Luxembourg', 1340),
    ('country', 'MO', 'Macao', 1350),
    ('country', 'MG', 'Madagascar', 1360),
    ('country', 'MW', 'Malawi', 1370),
    ('country', 'MY', 'Malaysia', 1380),
    ('country', 'MV', 'Maldives', 1390),
    ('country', 'ML', 'Mali', 1400),
    ('country', 'MT', 'Malta', 1410),
    ('country', 'MH', 'Marshall Islands', 1420),
    ('country', 'MQ', 'Martinique', 1430),
    ('country', 'MR', 'Mauritania', 1440),
    ('country', 'MU', 'Mauritius', 1450),
    ('country', 'YT', 'Mayotte', 1460),
    ('country', 'MX', 'Mexico', 1470),
    ('country', 'MC', 'Monaco', 1480),
    ('country', 'MN', 'Mongolia', 1490),
    ('country', 'ME', 'Montenegro', 1500),
    ('country', 'MS', 'Montserrat', 1510),
    ('country', 'MA', 'Morocco', 1520),
    ('country', 'MZ', 'Mozambique', 1530),
    ('country', 'MM', 'Myanmar', 1540),
    ('country', 'NA', 'Namibia', 1550),
    ('country', 'NR', 'Nauru', 1560),
    ('country', 'NP', 'Nepal', 1570),
    ('country', 'NL', 'Netherlands', 1580),
    ('country', 'US-NV', 'Nevada', 1590),
    ('country', 'NC', 'New Caledonia', 1600),
    ('country', 'US-NY', 'New York', 1610),
    ('country', 'NZ', 'New Zealand', 1620),
    ('country', 'NI', 'Nicaragua', 1630),
    ('country', 'NE', 'Niger', 1640),
    ('country', 'NG', 'Nigeria', 1650),
    ('country', 'NU', 'Niue', 1660),
    ('country', 'NF', 'Norfolk Island', 1670),
    ('country', 'GB-NIR', 'Northern Ireland', 1680),
    ('country', 'MP', 'Northern Mariana Islands', 1690),
    ('country', 'NO', 'Norway', 1700),
    ('country', 'OM', 'Oman', 1710),
    ('country', 'PK', 'Pakistan', 1720),
    ('country', 'PW', 'Palau', 1730),
    ('country', 'PS', 'Palestinian Territory, Occupied', 1740),
    ('country', 'PA', 'Panama', 1750),
    ('country', 'PG', 'Papua New Guinea', 1760),
    ('country', 'PY', 'Paraguay', 1770),
    ('country', 'PE', 'Peru', 1780),
    ('country', 'PH', 'Philippines', 1790),
    ('country', 'PN', 'Pitcairn', 1800),
    ('country', 'PL', 'Poland', 1810),
    ('country', 'PT', 'Portugal', 1820),
    ('country', 'PR', 'Puerto Rico', 1830),
    ('country', 'QA', 'Qatar', 1840),
    ('country', 'KR', 'Republic of Korea', 1850),
    ('country', 'MD', 'Republic of Moldova', 1860),
    ('country', 'RE', 'Reunion', 1870),
    ('country', 'RO', 'Romania', 1880),
    ('country', 'RU', 'Russian Federation', 1890),
    ('country', 'RW', 'Rwanda', 1900),
    ('country', 'BL', 'Saint Barthelemy', 1910),
    ('country', 'SH', 'Saint Helena', 1920),
    ('country', 'KN', 'Saint Kitts and Nevis', 1930),
    ('country', 'LC', 'Saint Lucia', 1940),
    ('country', 'MF', 'Saint Martin (French Part)', 1950),
    ('country', 'PM', 'Saint Pierre and Miquelon', 1960),
    ('country', 'VC', 'Saint Vincent and the Grenadines', 1970),
    ('country', 'WS', 'Samoa', 1980),
    ('country', 'SM', 'San Marino', 1990),
    ('country', 'ST', 'Sao Tome and Principe', 2000),
    ('country', 'GB-SAR', 'Sark C.I.', 2010),
    ('country', 'SA', 'Saudi Arabia', 2020),
    ('country', 'GB-SCT', 'Scotland', 2030),
    ('country', 'SN', 'Senegal', 2040),
    ('country', 'RS', 'Serbia', 2050),
    ('country', 'SC', 'Seychelles', 2060),
    ('country', 'SL', 'Sierra Leone', 2070),
    ('country', 'SG', 'Singapore', 2080),
    ('country', 'SX', 'Sint Maarten  (Dutch Part)', 2090),
    ('country', 'SK', 'Slovakia', 2100),
    ('country', 'SI', 'Slovenia', 2110),
    ('country', 'SB', 'Solomon Islands', 2120),
    ('country', 'SO', 'Somalia', 2130),
    ('country', 'ZA', 'South Africa', 2140),
    ('country', 'GS', 'South Georgia and the South Sandwich Islands', 2150),
    ('country', 'SS', 'South Sudan', 2160),
    ('country', 'ES', 'Spain', 2170),
    ('country', 'LK', 'Sri Lanka', 2180),
    ('country', 'US-CA', 'State of California', 2190),
    ('country', 'US-CT', 'State of Connecticut', 2200),
    ('country', 'US-FL', 'State of Florida', 2210),
    ('country', 'US-UT', 'State of Utah', 2220),
    ('country', 'SD', 'Sudan', 2230),
    ('country', 'SR', 'Suriname', 2240),
    ('country', 'SJ', 'Svalbard and Jan Mayen', 2250),
    ('country', 'SZ', 'Swaziland', 2260),
    ('country', 'SE', 'Sweden', 2270),
    ('country', 'CH', 'Switzerland', 2280),
    ('country', 'SY', 'Syrian Arab Republic', 2290),
    ('country', 'TW', 'Taiwan', 2300),
    ('country', 'TJ', 'Tajikistan', 2310),
    ('country', 'TH', 'Thailand', 2320),
    ('country', 'CD', 'The Democratic Republic of the Congo', 2330),
    ('country', 'MK', 'The Former Yugoslav Republic of Macedonia', 2340),
    ('country', 'TL', 'Timor-Leste', 2350),
    ('country', 'TG', 'Togo', 2360),
    ('country', 'TK', 'Tokelau', 2370),
    ('country', 'TO', 'Tonga', 2380),
    ('country', 'TT', 'Trinidad and Tobago', 2390),
    ('country', 'TN', 'Tunisia', 2400),
    ('country', 'TR', 'Turkey', 2410),
    ('country', 'TM', 'Turkmenistan', 2420),
    ('country', 'TC', 'Turks and Caicos Islands', 2430),
    ('country', 'TV', 'Tuvalu', 2440),
    ('country', 'UG', 'Uganda', 2450),
    ('country', 'UA', 'Ukraine', 2460),
    ('country', 'AE', 'United Arab Emirates', 2470),
    ('country', 'GB', 'United Kingdom', 2480),
    ('country', 'TZ', 'United Republic of Tanzania', 2490),
    ('country', 'US', 'United States', 2500),
    ('country', 'UM', 'United States Minor Outlying Islands', 2510),
    ('country', 'UY', 'Uruguay', 2520),
    ('country', 'VI', 'US Virgin Islands', 2530),
    ('country', 'UZ', 'Uzbekistan', 2540),
    ('country', 'VU', 'Vanuatu', 2550),
    ('country', 'VA', 'Vatican City State (Holy See)', 2560),
    ('country', 'VE', 'Venezuela', 2570),
    ('country', 'VN', 'Vietnam', 2580),
    ('country', 'GB-WLS', 'Wales', 2590),
    ('country', 'WF', 'Wallis and Futuna Islands', 2600),
    ('country', 'EH', 'Western Sahara', 2610),
    ('country', 'US-WY', 'Wyoming', 2620),
    ('country', 'YE', 'Yemen', 2630),
    ('country', 'ZR', 'Zaire', 2640),
    ('country', 'ZM', 'Zambia', 2650),
    ('country', 'ZW', 'Zimbabwe', 2660),
    ('country', 'TW-CH', '台灣', 2670),
    ('country', 'MO-CH', '澳門', 2680),
    ('country', 'HK-CH', '香港', 2690),
    ('currency', 'XUA', 'ADB Unit of Account', 0),
    ('currency', 'AFN', 'Afghani', 10),
    ('currency', 'DZD', 'Algerian Dinar', 20),
    ('currency', 'ARS', 'Argentine Peso', 30),
    ('currency', 'AMD', 'Armenian Dram', 40),
    ('currency', 'AWG', 'Aruban Florin', 50),
    ('currency', 'AUD', 'Australian Dollar', 60),
    ('currency', 'AZN', 'Azerbaijan Manat', 70),
    ('currency', 'BSD', 'Bahamian Dollar', 80),
    ('currency', 'BHD', 'Bahraini Dinar', 90),
    ('currency', 'THB', 'Baht', 100),
    ('currency', 'PAB', 'Balboa', 110),
    ('currency', 'BBD', 'Barbados Dollar', 120),
    ('currency', 'BYN', 'Belarusian Ruble', 130),
    ('currency', 'BZD', 'Belize Dollar', 140),
    ('currency', 'BMD', 'Bermudian Dollar', 150),
    ('currency', 'VES', 'Bolívar Soberano', 160),
    ('currency', 'BOB', 'Boliviano', 170),
    ('currency', 'BRL', 'Brazilian Real', 180),
    ('currency', 'BND', 'Brunei Dollar', 190),
    ('currency', 'BGN', 'Bulgarian Lev', 200),
    ('currency', 'BIF', 'Burundi Franc', 210),
    ('currency', 'CVE', 'Cabo Verde Escudo', 220),
    ('currency', 'CAD', 'Canadian Dollar', 230),
    ('currency', 'KYD', 'Cayman Islands Dollar', 240),
    ('currency', 'XOF', 'CFA Franc BCEAO', 250),
    ('currency', 'XAF', 'CFA Franc BEAC', 260),
    ('currency', 'XPF', 'CFP Franc', 270),
    ('currency', 'CLP', 'Chilean Peso', 280),
    ('currency', 'COP', 'Colombian Peso', 290),
    ('currency', 'KMF', 'Comorian Franc', 300),
    ('currency', 'CDF', 'Congolese Franc', 310),
    ('currency', 'BAM', 'Convertible Mark', 320),
    ('currency', 'NIO', 'Cordoba Oro', 330),
    ('currency', 'CRC', 'Costa Rican Colon', 340),
    ('currency', 'CUP', 'Cuban Peso', 350),
    ('currency', 'CZK', 'Czech Koruna', 360),
    ('currency', 'GMD', 'Dalasi', 370),
    ('currency', 'DKK', 'Danish Krone', 380),
    ('currency', 'MKD', 'Denar', 390),
    ('currency', 'DJF', 'Djibouti Franc', 400),
    ('currency', 'STN', 'Dobra', 410),
    ('currency', 'DOP', 'Dominican Peso', 420),
    ('currency', 'VND', 'Dong', 430),
    ('currency', 'XCD', 'East Caribbean Dollar', 440),
    ('currency', 'EGP', 'Egyptian Pound', 450),
    ('currency', 'SVC', 'El Salvador Colon', 460),
    ('currency', 'ETB', 'Ethiopian Birr', 470),
    ('currency', 'EUR', 'Euro', 480),
    ('currency', 'FKP', 'Falkland Islands Pound', 490),
    ('currency', 'FJD', 'Fiji Dollar', 500),
    ('currency', 'HUF', 'Forint', 510),
    ('currency', 'GHS', 'Ghana Cedi', 520),
    ('currency', 'GIP', 'Gibraltar Pound', 530),
    ('currency', 'HTG', 'Gourde', 540),
    ('currency', 'PYG', 'Guarani', 550),
    ('currency', 'GNF', 'Guinean Franc', 560),
    ('currency', 'GYD', 'Guyana Dollar', 570),
    ('currency', 'HKD', 'Hong Kong Dollar', 580),
    ('currency', 'UAH', 'Hryvnia', 590),
    ('currency', 'ISK', 'Iceland Krona', 600),
    ('currency', 'INR', 'Indian Rupee', 610),
    ('currency', 'IRR', 'Iranian Rial', 620),
    ('currency', 'IQD', 'Iraqi Dinar', 630),
    ('currency', 'JMD', 'Jamaican Dollar', 640),
    ('currency', 'JOD', 'Jordanian Dinar', 650),
    ('currency', 'KES', 'Kenyan Shilling', 660),
    ('currency', 'PGK', 'Kina', 670),
    ('currency', 'HRK', 'Kuna', 680),
    ('currency', 'KWD', 'Kuwaiti Dinar', 690),
    ('currency', 'AOA', 'Kwanza', 700),
    ('currency', 'MMK', 'Kyat', 710),
    ('currency', 'LAK', 'Lao Kip', 720),
    ('currency', 'GEL', 'Lari', 730),
    ('currency', 'LBP', 'Lebanese Pound', 740),
    ('currency', 'ALL', 'Lek', 750),
    ('currency', 'HNL', 'Lempira', 760),
    ('currency', 'SLL', 'Leone', 770),
    ('currency', 'LRD', 'Liberian Dollar', 780),
    ('currency', 'LYD', 'Libyan Dinar', 790),
    ('currency', 'SZL', 'Lilangeni', 800),
    ('currency', 'LSL', 'Loti', 810),
    ('currency', 'MGA', 'Malagasy Ariary', 820),
    ('currency', 'MWK', 'Malawi Kwacha', 830),
    ('currency', 'MYR', 'Malaysian Ringgit', 840),
    ('currency', 'MUR', 'Mauritius', 850),
    ('currency', 'MXN', 'Mexican Peso', 860),
    ('currency', 'MDL', 'Moldovan Leu', 870),
    ('currency', 'MAD', 'Moroccan Dirham', 880),
    ('currency', 'MZN', 'Mozambique Metical', 890),
    ('currency', 'BOV', 'Mvdol', 900),
    ('currency', 'NGN', 'Naira', 910),
    ('currency', 'ERN', 'Nakfa', 920),
    ('currency', 'NAD', 'Namibia Dollar', 930),
    ('currency', 'NPR', 'Nepalese Rupee', 940),
    ('currency', 'ANG', 'Netherlands Antillean Guilder', 950),
    ('currency', 'ILS', 'New Israeli Sheqel', 960),
    ('currency', 'NZD', 'New Zealand Dollar', 970),
    ('currency', 'BTN', 'Ngultrum', 980),
    ('currency', 'KPW', 'North Korean Won', 990),
    ('currency', 'NOK', 'Norwegian Krone', 1000),
    ('currency', 'MRU', 'Ouguiya', 1010),
    ('currency', 'TOP', 'Pa’anga', 1020),
    ('currency', 'PKR', 'Pakistan Rupee', 1030),
    ('currency', 'MOP', 'Pataca', 1040),
    ('currency', 'CUC', 'Peso Convertible', 1050),
    ('currency', 'UYU', 'Peso Uruguayo', 1060),
    ('currency', 'PHP', 'Philippine Peso', 1070),
    ('currency', 'GBP', 'Pound Sterling', 1080),
    ('currency', 'BWP', 'Pula', 1090),
    ('currency', 'QAR', 'Qatari Rial', 1100),
    ('currency', 'ZAR', 'Rand', 1110),
    ('currency', 'OMR', 'Rial Omani', 1120),
    ('currency', 'KHR', 'Riel', 1130),
    ('currency', 'RON', 'Romanian Leu', 1140),
    ('currency', 'MVR', 'Rufiyaa', 1150),
    ('currency', 'IDR', 'Rupiah', 1160),
    ('currency', 'RUB', 'Russian Rouble', 1170),
    ('currency', 'RWF', 'Rwanda Franc', 1180),
    ('currency', 'SHP', 'Saint Helena Pound', 1190),
    ('currency', 'RSD', 'Serbian Dinar', 1200),
    ('currency', 'SCR', 'Seychelles', 1210),
    ('currency', 'SGD', 'Singapore Dollar', 1220),
    ('currency', 'PEN', 'Sol', 1230),
    ('currency', 'SBD', 'Solomon Islands Dollar', 1240),
    ('currency', 'KGS', 'Som', 1250),
    ('currency', 'SOS', 'Somali Shilling', 1260),
    ('currency', 'TJS', 'Somoni', 1270),
    ('currency', 'SSP', 'South Sudanese Pound', 1280),
    ('currency', 'LKR', 'Sri Lanka Rupee', 1290),
    ('currency', 'XSU', 'Sucre', 1300),
    ('currency', 'SDG', 'Sudanese Pound', 1310),
    ('currency', 'SRD', 'Surinam Dollar', 1320),
    ('currency', 'SEK', 'Swedish Krona', 1330),
    ('currency', 'CHF', 'Swiss Franc', 1340),
    ('currency', 'SYP', 'Syrian Pound', 1350),
    ('currency', 'TWD', 'Taiwan New Dollar', 1360),
    ('currency', 'BDT', 'Taka', 1370),
    ('currency', 'WST', 'Tala', 1380),
    ('currency', 'TZS', 'Tanzanian Shilling', 1390),
    ('currency', 'KZT', 'Tenge', 1400),
    ('currency', 'TTD', 'Trinidad and Tobago Dollar', 1410),
    ('currency', 'MNT', 'Tugrik', 1420),
    ('currency', 'TND', 'Tunisian Dinar', 1430),
    ('currency', 'TRY', 'Turkish Lira', 1440),
    ('currency', 'TMT', 'Turkmenistan New Manat', 1450),
    ('currency', 'AED', 'UAE Dirham', 1460),
    ('currency', 'UGX', 'Uganda Shilling', 1470),
    ('currency', 'CLF', 'Unidad de Fomento', 1480),
    ('currency', 'COU', 'Unidad de Valor Real', 1490),
    ('currency', 'USD', 'US Dollar', 1500),
    ('currency', 'UZS', 'Uzbekistan Sum', 1510),
    ('currency', 'VUV', 'Vatu', 1520),
    ('currency', 'CHE', 'WIR Euro', 1530),
    ('currency', 'CHW', 'WIR Franc', 1540),
    ('currency', 'KRW', 'Won', 1550),
    ('currency', 'YER', 'Yemeni Rial', 1560),
    ('currency', 'JPY', 'Yen', 1570),
    ('currency', 'CNY', 'Yuan Renminbi', 1580),
    ('currency', 'ZMW', 'Zambian Kwacha', 1590),
    ('currency', 'ZWL', 'Zimbabwe Dollar', 1600),
    ('currency', 'PLN', 'Zloty', 1610),
    ('entity_status', '0', 'Active', 0),
    ('entity_status', 'C', 'Closed', 10),
    ('entity_status', 'G', 'Closing', 20),
    ('officer_status', 'A', 'Appointed', 0),
    ('officer_status', 'R', 'Resigned', 10),
    ('party_type', 'C', 'Company', 0),
    ('party_type', 'I', 'Individual', 10),
    ('party_type', 'O', 'Other (non individual)', 20),
    ('party_type', 'P', 'Partnership', 30),
    ('party_type', 'T', 'Trust', 40),
    ('address_type', 'BA', 'Business Address', 0),
    ('address_type', 'SU', 'Company Stamp', 10),
    ('address_type', 'SA', 'Copies of Instruments Creating Charges', 20),
    ('address_type', 'S2', 'Copy of Management Contract', 30),
    ('address_type', 'S1', 'Copy of Permitted Indemnity Provision', 40),
    ('address_type', 'RC', 'Correspondence Address', 50),
    ('address_type', 'SS', 'Location of Common Seal', 60),
    ('address_type', 'ST', 'Location of Duplicate Seal', 70),
    ('address_type', 'MA', 'Mailing Address', 80),
    ('address_type', 'SI', 'Minute Book', 90),
    ('address_type', 'SB', 'Principal Place of Business', 100),
    ('address_type', 'SC', 'Register of Charges', 110),
    ('address_type', 'SG', 'Register of Company Secretaries', 120),
    ('address_type', 'SD', 'Register of Debenture Holders', 130),
    ('address_type', 'SH', 'Register of Directors', 140),
    ('address_type', 'SO', 'Register of Directors/Secretaries', 150),
    ('address_type', 'SM', 'Register of Members', 160),
    ('address_type', 'S3', 'Register of Particulars Referred to in section 384', 170),
    ('address_type', 'SR', 'Registered Office of Company', 180),
    ('address_type', 'RO', 'Registered Office of Master File', 190),
    ('address_type', 'RA', 'Residential Address', 200),
    ('address_type', 'SQ', 'Significant Controllers Register', 210),
    ('nationality', 'Afghan', 'Afghan', 0),
    ('nationality', 'Albanian', 'Albanian', 10),
    ('nationality', 'Algerian', 'Algerian', 20),
    ('nationality', 'American', 'American', 30),
    ('nationality', 'Andorran', 'Andorran', 40),
    ('nationality', 'Angolan', 'Angolan', 50),
    ('nationality', 'Antiguan', 'Antiguan', 60),
    ('nationality', 'Argentine', 'Argentine', 70),
    ('nationality', 'Armenian', 'Armenian', 80),
    ('nationality', 'Australian', 'Australian', 90),
    ('nationality', 'Austrian', 'Austrian', 100),
    ('nationality', 'Azerbaijani', 'Azerbaijani', 110),
    ('nationality', 'Bahamian', 'Bahamian', 120),
    ('nationality', 'Bahraini', 'Bahraini', 130),
    ('nationality', 'Bangladeshi', 'Bangladeshi', 140),
    ('nationality', 'Barbadian', 'Barbadian', 150),
    ('nationality', 'Belarusian', 'Belarusian', 160),
    ('nationality', 'Belgian', 'Belgian', 170),
    ('nationality', 'Belizean', 'Belizean', 180),
    ('nationality', 'Beninese', 'Beninese', 190),
    ('nationality', 'Bhutanese', 'Bhutanese', 200),
    ('nationality', 'Bolivian', 'Bolivian', 210),
    ('nationality', 'Bosnian', 'Bosnian', 220),
    ('nationality', 'Botswanan', 'Botswanan', 230),
    ('nationality', 'Brazilian', 'Brazilian', 240),
    ('nationality', 'British', 'British', 250),
    ('nationality', 'Bruneian', 'Bruneian', 260),
    ('nationality', 'Bulgarian', 'Bulgarian', 270),
    ('nationality', 'Burkinabe', 'Burkinabe', 280),
    ('nationality', 'Burundian', 'Burundian', 290),
    ('nationality', 'Cambodian', 'Cambodian', 300),
    ('nationality', 'Cameroonian', 'Cameroonian', 310),
    ('nationality', 'Canadian', 'Canadian', 320),
    ('nationality', 'Cape Verdean', 'Cape Verdean', 330),
    ('nationality', 'Chadian', 'Chadian', 340),
    ('nationality', 'Chilean', 'Chilean', 350),
    ('nationality', 'Chinese', 'Chinese', 360),
    ('nationality', 'Colombian', 'Colombian', 370),
    ('nationality', 'Comoran', 'Comoran', 380),
    ('nationality', 'Congolese', 'Congolese', 390),
    ('nationality', 'Costa Rican', 'Costa Rican', 400),
    ('nationality', 'Croatian', 'Croatian', 410),
    ('nationality', 'Cuban', 'Cuban', 420),
    ('nationality', 'Cypriot', 'Cypriot', 430),
    ('nationality', 'Czech', 'Czech', 440),
    ('nationality', 'Danish', 'Danish', 450),
    ('nationality', 'Djiboutian', 'Djiboutian', 460),
    ('nationality', 'Dominican', 'Dominican', 470),
    ('nationality', 'Dutch', 'Dutch', 480),
    ('nationality', 'Ecuadorean', 'Ecuadorean', 490),
    ('nationality', 'Egyptian', 'Egyptian', 500),
    ('nationality', 'Emirian', 'Emirian', 510),
    ('nationality', 'Eritrean', 'Eritrean', 520),
    ('nationality', 'Estonian', 'Estonian', 530),
    ('nationality', 'Ethiopian', 'Ethiopian', 540),
    ('nationality', 'Fijian', 'Fijian', 550),
    ('nationality', 'Filipino', 'Filipino', 560),
    ('nationality', 'Finnish', 'Finnish', 570),
    ('nationality', 'French', 'French', 580),
    ('nationality', 'Gabonese', 'Gabonese', 590),
    ('nationality', 'Gambian', 'Gambian', 600),
    ('nationality', 'Georgian', 'Georgian', 610),
    ('nationality', 'German', 'German', 620),
    ('nationality', 'Ghanaian', 'Ghanaian', 630),
    ('nationality', 'Greek', 'Greek', 640),
    ('nationality', 'Grenadian', 'Grenadian', 650),
    ('nationality', 'Guatemalan', 'Guatemalan', 660),
    ('nationality', 'Guinean', 'Guinean', 670),
    ('nationality', 'Guyanese', 'Guyanese', 680),
    ('nationality', 'Haitian', 'Haitian', 690),
    ('nationality', 'Honduran', 'Honduran', 700),
    ('nationality', 'Hong Kong', 'Hong Kong', 710),
    ('nationality', 'Hungarian', 'Hungarian', 720),
    ('nationality', 'Icelandic', 'Icelandic', 730),
    ('nationality', 'Indian', 'Indian', 740),
    ('nationality', 'Indonesian', 'Indonesian', 750),
    ('nationality', 'Iranian', 'Iranian', 760),
    ('nationality', 'Iraqi', 'Iraqi', 770),
    ('nationality', 'Irish', 'Irish', 780),
    ('nationality', 'Israeli', 'Israeli', 790),
    ('nationality', 'Italian', 'Italian', 800),
    ('nationality', 'Ivorian', 'Ivorian', 810),
    ('nationality', 'Jamaican', 'Jamaican', 820),
    ('nationality', 'Japanese', 'Japanese', 830),
    ('nationality', 'Jordanian', 'Jordanian', 840),
    ('nationality', 'Kazakhstani', 'Kazakhstani', 850),
    ('nationality', 'Kenyan', 'Kenyan', 860),
    ('nationality', 'Kittian', 'Kittian', 870),
    ('nationality', 'Kuwaiti', 'Kuwaiti', 880),
    ('nationality', 'Kyrgyzstani', 'Kyrgyzstani', 890),
    ('nationality', 'Laotian', 'Laotian', 900),
    ('nationality', 'Latvian', 'Latvian', 910),
    ('nationality', 'Lebanese', 'Lebanese', 920),
    ('nationality', 'Lesotho', 'Lesotho', 930),
    ('nationality', 'Liberian', 'Liberian', 940),
    ('nationality', 'Libyan', 'Libyan', 950),
    ('nationality', 'Liechtensteiner', 'Liechtensteiner', 960),
    ('nationality', 'Lithunian', 'Lithunian', 970),
    ('nationality', 'Luxembourgish', 'Luxembourgish', 980),
    ('nationality', 'Macedonian', 'Macedonian', 990),
    ('nationality', 'Malagasy', 'Malagasy', 1000),
    ('nationality', 'Malawian', 'Malawian', 1010),
    ('nationality', 'Malaysian', 'Malaysian', 1020),
    ('nationality', 'Maldivian', 'Maldivian', 1030),
    ('nationality', 'Malian', 'Malian', 1040),
    ('nationality', 'Maltese', 'Maltese', 1050),
    ('nationality', 'Marino', 'Marino', 1060),
    ('nationality', 'Marshallese', 'Marshallese', 1070),
    ('nationality', 'Mauritanian', 'Mauritanian', 1080),
    ('nationality', 'Mauritian', 'Mauritian', 1090),
    ('nationality', 'Mexican', 'Mexican', 1100),
    ('nationality', 'Micronesian', 'Micronesian', 1110),
    ('nationality', 'Moldovan', 'Moldovan', 1120),
    ('nationality', 'Monacan', 'Monacan', 1130),
    ('nationality', 'Mongolian', 'Mongolian', 1140),
    ('nationality', 'Montenegrin', 'Montenegrin', 1150),
    ('nationality', 'Moroccan', 'Moroccan', 1160),
    ('nationality', 'Mozambican', 'Mozambican', 1170),
    ('nationality', 'Myanmarese', 'Myanmarese', 1180),
    ('nationality', 'Namibian', 'Namibian', 1190),
    ('nationality', 'Nauruan', 'Nauruan', 1200),
    ('nationality', 'Nepalese', 'Nepalese', 1210),
    ('nationality', 'New Zealander', 'New Zealander', 1220),
    ('nationality', 'Ni-Vanuatu', 'Ni-Vanuatu', 1230),
    ('nationality', 'Nicaraguan', 'Nicaraguan', 1240),
    ('nationality', 'Nigerian', 'Nigerian', 1250),
    ('nationality', 'Nigerien', 'Nigerien', 1260),
    ('nationality', 'North Korean', 'North Korean', 1270),
    ('nationality', 'Norwegian', 'Norwegian', 1280),
    ('nationality', 'Omani', 'Omani', 1290),
    ('nationality', 'Pakistani', 'Pakistani', 1300),
    ('nationality', 'Palauan', 'Palauan', 1310),
    ('nationality', 'Palestinian', 'Palestinian', 1320),
    ('nationality', 'Panamanian', 'Panamanian', 1330),
    ('nationality', 'Papua New Guinean', 'Papua New Guinean', 1340),
    ('nationality', 'Paraguayan', 'Paraguayan', 1350),
    ('nationality', 'Peruvian', 'Peruvian', 1360),
    ('nationality', 'Polish', 'Polish', 1370),
    ('nationality', 'Portuguese', 'Portuguese', 1380),
    ('nationality', 'Qatari', 'Qatari', 1390),
    ('nationality', 'Romanian', 'Romanian', 1400),
    ('nationality', 'Russian', 'Russian', 1410),
    ('nationality', 'Rwandan', 'Rwandan', 1420),
    ('nationality', 'Salvadoran', 'Salvadoran', 1430),
    ('nationality', 'Samoan', 'Samoan', 1440),
    ('nationality', 'Sao Tomean', 'Sao Tomean', 1450),
    ('nationality', 'Saudi Arabian', 'Saudi Arabian', 1460),
    ('nationality', 'Senegalese', 'Senegalese', 1470),
    ('nationality', 'Serbian', 'Serbian', 1480),
    ('nationality', 'Seychellois', 'Seychellois', 1490),
    ('nationality', 'Sierra Leonean', 'Sierra Leonean', 1500),
    ('nationality', 'Singaporean', 'Singaporean', 1510),
    ('nationality', 'Slovakian', 'Slovakian', 1520),
    ('nationality', 'Slovenian', 'Slovenian', 1530),
    ('nationality', 'Solomon Islander', 'Solomon Islander', 1540),
    ('nationality', 'Somali', 'Somali', 1550),
    ('nationality', 'South African', 'South African', 1560),
    ('nationality', 'South Korean', 'South Korean', 1570),
    ('nationality', 'South Sudanese', 'South Sudanese', 1580),
    ('nationality', 'Spanish', 'Spanish', 1590),
    ('nationality', 'Sri Lankan', 'Sri Lankan', 1600),
    ('nationality', 'Sudanese', 'Sudanese', 1610),
    ('nationality', 'Surinamese', 'Surinamese', 1620),
    ('nationality', 'Swazi', 'Swazi', 1630),
    ('nationality', 'Swedish', 'Swedish', 1640),
    ('nationality', 'Swiss', 'Swiss', 1650),
    ('nationality', 'Syrian', 'Syrian', 1660),
    ('nationality', 'Taiwanese', 'Taiwanese', 1670),
    ('nationality', 'Tajikistani', 'Tajikistani', 1680),
    ('nationality', 'Tanzanian', 'Tanzanian', 1690),
    ('nationality', 'Thai', 'Thai', 1700),
    ('nationality', 'Timorese', 'Timorese', 1710),
    ('nationality', 'Togolese', 'Togolese', 1720),
    ('nationality', 'Tongan', 'Tongan', 1730),
    ('nationality', 'Trinidadian', 'Trinidadian', 1740),
    ('nationality', 'Tunisian', 'Tunisian', 1750),
    ('nationality', 'Turkish', 'Turkish', 1760),
    ('nationality', 'Turkmen', 'Turkmen', 1770),
    ('nationality', 'Tuvaluan', 'Tuvaluan', 1780),
    ('nationality', 'Ugandan', 'Ugandan', 1790),
    ('nationality', 'Ukrainian', 'Ukrainian', 1800),
    ('nationality', 'Uruguayan', 'Uruguayan', 1810),
    ('nationality', 'Uzbekistani', 'Uzbekistani', 1820),
    ('nationality', 'Vatican', 'Vatican', 1830),
    ('nationality', 'Venezuelan', 'Venezuelan', 1840),
    ('nationality', 'Vietnamese', 'Vietnamese', 1850),
    ('nationality', 'Yemeni', 'Yemeni', 1860),
    ('nationality', 'Zambian', 'Zambian', 1870),
    ('nationality', 'Zimbabwean', 'Zimbabwean', 1880),
]

# Which owner a document type can be attached to.
DOC_SCOPE = {
    "nar1": "company", "nnc1": "company", "aoa": "company", "fwr": "company",
    "coi": "company", "incumbency": "company", "share_certificate": "company",
    "id_scan": "person",
    "address_proof": "both", "other": "both",
}

# The seed in 003 wrote these through a cp1252 round-trip and mangled the em-dash.
LABEL_FIXES = {
    "nar1": "NAR1 — Annual Return",
    "nnc1": "NNC1 — Incorporation Form",
}


def upgrade() -> None:
    op.create_table(
        "lookup_values",
        sa.Column("category", sa.Text, nullable=False),
        sa.Column("code", sa.Text, nullable=False),
        sa.Column("label", sa.Text, nullable=False),
        sa.Column("sort_order", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.PrimaryKeyConstraint("category", "code"),
    )
    op.create_index(
        "ix_lookup_values_category",
        "lookup_values", ["category", "sort_order"],
        postgresql_where=sa.text("is_active"),
    )
    op.bulk_insert(
        sa.table(
            "lookup_values",
            sa.column("category", sa.Text), sa.column("code", sa.Text),
            sa.column("label", sa.Text), sa.column("sort_order", sa.Integer),
        ),
        [{"category": c, "code": k, "label": l, "sort_order": s} for c, k, l, s in LOOKUPS],
    )

    op.add_column(
        "document_types",
        sa.Column("applies_to", sa.Text, nullable=False, server_default="both"),
    )
    op.create_check_constraint(
        "document_types_applies_to_valid", "document_types",
        "applies_to IN ('company', 'person', 'both')",
    )
    for code, scope in DOC_SCOPE.items():
        op.execute(
            sa.text("UPDATE document_types SET applies_to = :s WHERE code = :c")
            .bindparams(s=scope, c=code)
        )
    for code, label in LABEL_FIXES.items():
        op.execute(
            sa.text("UPDATE document_types SET label = :l WHERE code = :c")
            .bindparams(l=label, c=code)
        )

    # Supabase-only roles; CI runs vanilla Postgres where they do not exist.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                GRANT SELECT ON lookup_values TO authenticated;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
                GRANT SELECT ON lookup_values TO service_role;
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    op.drop_constraint("document_types_applies_to_valid", "document_types")
    op.drop_column("document_types", "applies_to")
    op.drop_index("ix_lookup_values_category", table_name="lookup_values")
    op.drop_table("lookup_values")
